name: Test and Lint React Code on Push

on: 
  push:
    branches:
      - main          # Trigger on push to the 'main' branch
      - 'feature/*'   # Optionally, trigger on feature branches as well

jobs:
  first_job:
    runs-on: ubuntu-latest  # Use GitHub's latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can change this if you use another version of Node.js

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run ESLint (assuming you have a lint script defined in package.json)
      - name: Run ESLint
        run: |
          npm run lint  # Ensure you have this script in your package.json
